name: Validate PR Source

on:
  pull_request:
    branches: [ main ]  # Solo PRs hacia main
    types: [opened, synchronize, reopened]

jobs:
  validate-source:
    runs-on: ubuntu-latest
    name: Validate PR comes from develop
    # Condición adicional para asegurar que solo corra para PRs hacia main
    if: github.base_ref == 'main'
    steps:
    - name: Check PR source branch
      run: |
        echo "🔍 Checking PR source branch..."
        echo "Source branch: ${{ github.head_ref }}"
        echo "Target branch: ${{ github.base_ref }}"
        echo "Event action: ${{ github.event.action }}"
        echo "Repository default branch: ${{ github.event.repository.default_branch }}"
        
        # Verificación de seguridad - solo debe ejecutarse para PRs hacia main
        if [ "${{ github.base_ref }}" != "main" ]; then
          echo ""
          echo "⚠️  WARNING: This workflow should only run for PRs targeting 'main' branch"
          echo "⚠️  Current target branch: ${{ github.base_ref }}"
          echo "⚠️  Skipping validation..."
          echo ""
          exit 0
        fi
        
        # Validación principal: el PR hacia main debe venir desde develop
        if [ "${{ github.head_ref }}" != "develop" ]; then
          echo ""
          echo "❌ ERROR: Pull requests to main branch must come from develop branch only!"
          echo "❌ Current source branch: ${{ github.head_ref }}"
          echo "❌ Expected source branch: develop"
          echo ""
          echo "🔄 Please:"
          echo "1. Close this PR"
          echo "2. Merge your changes to develop first"
          echo "3. Create a new PR from develop to main"
          echo ""
          exit 1
        else
          echo ""
          echo "✅ SUCCESS: Pull request source validated!"
          echo "✅ develop → main is allowed"
          echo "✅ This PR follows the correct GitFlow pattern"
          echo ""
        fi