name: Validate PR Source
on:
  pull_request:
    branches: [ main ]  # Solo PRs hacia main
    types: [opened, synchronize, reopened]

jobs:
  validate-source:
    runs-on: ubuntu-latest
    name: Validate PR comes from develop
    # Condición MUY estricta para asegurar que SOLO corra para PRs hacia main
    if: github.base_ref == 'main'
    steps:
    - name: Debug Information
      run: |
        echo "🔍 DEBUG INFORMATION:"
        echo "github.base_ref: '${{ github.base_ref }}'"
        echo "github.head_ref: '${{ github.head_ref }}'"
        echo "github.event.pull_request.base.ref: '${{ github.event.pull_request.base.ref }}'"
        echo "github.event.pull_request.head.ref: '${{ github.event.pull_request.head.ref }}'"
        echo "Event action: ${{ github.event.action }}"
        echo ""
        
    - name: Early Exit Check
      run: |
        if [ "${{ github.base_ref }}" != "main" ]; then
          echo "⚠️  This workflow should ONLY run for PRs targeting 'main'"
          echo "⚠️  Current target: ${{ github.base_ref }}"
          echo "⚠️  Expected target: main"
          echo "⚠️  EXITING - This workflow should not have triggered!"
          echo ""
          echo "::error::Workflow triggered incorrectly. Check your workflow configuration."
          exit 1
        fi
        
    - name: Check PR source branch
      run: |
        echo "🔍 Checking PR source branch..."
        echo "Source branch: ${{ github.head_ref }}"
        echo "Target branch: ${{ github.base_ref }}"
        echo "Event action: ${{ github.event.action }}"
        echo "Repository default branch: ${{ github.event.repository.default_branch }}"
        
        # Validación principal: el PR hacia main debe venir desde develop
        if [ "${{ github.head_ref }}" != "develop" ]; then
          echo ""
          echo "❌ ERROR: Pull requests to main branch must come from develop branch only!"
          echo "❌ Current source branch: ${{ github.head_ref }}"
          echo "❌ Expected source branch: develop"
          echo ""
          echo "🔄 Please:"
          echo "1. Close this PR"
          echo "2. Merge your changes to develop first"
          echo "3. Create a new PR from develop to main"
          echo ""
          exit 1
        else
          echo ""
          echo "✅ SUCCESS: Pull request source validated!"
          echo "✅ develop → main is allowed"
          echo "✅ This PR follows the correct GitFlow pattern"
          echo ""
        fi
