name: Validate PR Source
on:
  pull_request:
    branches: [ main ]  # Solo PRs hacia main
    types: [opened, synchronize, reopened]

jobs:
  validate-source:
    runs-on: ubuntu-latest
    name: Validate PR comes from develop
    # Doble verificación para asegurar que realmente va hacia main
    if: github.base_ref == 'main'
    steps:
    - name: Get Current PR Info
      id: pr_info
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          console.log('PR Info from API:');
          console.log('- Head branch:', pr.head.ref);
          console.log('- Base branch:', pr.base.ref);
          console.log('- PR URL:', pr.html_url);
          
          return {
            head_ref: pr.head.ref,
            base_ref: pr.base.ref,
            pr_url: pr.html_url
          };
    
    - name: Debug Information
      run: |
        echo "🔍 DEBUG INFORMATION:"
        echo "Context github.base_ref: '${{ github.base_ref }}'"
        echo "Context github.head_ref: '${{ github.head_ref }}'"
        echo "API base_ref: '${{ fromJSON(steps.pr_info.outputs.result).base_ref }}'"
        echo "API head_ref: '${{ fromJSON(steps.pr_info.outputs.result).head_ref }}'"
        echo "Event action: ${{ github.event.action }}"
        echo ""
        
    - name: Validate Target Branch
      run: |
        API_BASE_REF="${{ fromJSON(steps.pr_info.outputs.result).base_ref }}"
        API_HEAD_REF="${{ fromJSON(steps.pr_info.outputs.result).head_ref }}"
        
        echo "🎯 Current PR target (from API): $API_BASE_REF"
        
        # Si el PR realmente NO va hacia main, salir sin error
        if [ "$API_BASE_REF" != "main" ]; then
          echo ""
          echo "✅ PR target is '$API_BASE_REF', not 'main'"
          echo "✅ This workflow should only validate PRs targeting 'main'"
          echo "✅ Skipping validation - this is correct GitFlow behavior"
          echo ""
          echo "ℹ️  Note: This workflow triggered due to initial configuration,"
          echo "ℹ️  but the PR target has been changed. This is normal."
          exit 0
        fi
        
        echo "🔍 PR is targeting 'main' - proceeding with validation..."
        
        # Validación para PRs hacia main
        if [ "$API_HEAD_REF" != "develop" ]; then
          echo ""
          echo "❌ ERROR: Pull requests to main branch must come from develop branch only!"
          echo "❌ Current source branch: $API_HEAD_REF"
          echo "❌ Expected source branch: develop"
          echo ""
          echo "🔄 GitFlow Process:"
          echo "1. Close this PR"
          echo "2. Create PR: $API_HEAD_REF → develop"
          echo "3. After approval and merge"
          echo "4. Create PR: develop → main"
          echo ""
          exit 1
        else
          echo ""
          echo "✅ SUCCESS: Pull request source validated!"
          echo "✅ develop → main follows correct GitFlow pattern"
          echo "✅ This PR is ready for release deployment"
          echo ""
        fi
